version: '2'
services:
  api:
    build: .
    image: 2j3j_front
    container_name: 2j3j_front_con
    ports:
      - 8080:80
    networks:
          - 2j3j-network
networks:
  2j3j-network:
    external: true